title: Matsci Odia Requirements Documentation
description: Functional Requirements and Specifications for Matsci Odia Platform
theme: just-the-docs
show_downloads: false
markdown: kramdown
baseurl: "/project-requirements"
